using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace MusicStore.Migrations
{
    /// <inheritdoc />
    public partial class PopularInstrumento : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("INSERT INTO Instrumentos(CategoriaId,Resumo,ResumoDetalhada,EmEstoque,ImagemThumbnailUrl,ImagemUrl,Destaque,InstrumentoNome,Preco) VALUES(1,'Guitarra Strinberg Les Paul LPS230 BK - Preto','Guitarra modelo Les Paul de timbre encorpado, diversas opções de cores e com tocabilidade confortável. Possui 2 captadores duplos, braço parafusado, chave de 3 posições e ponte fixa.',1, 'https://madeinbrazil.fbitsstatic.net/img/p/guitarra-strinberg-les-paul-lps230-bk-preto-130359/343429.jpg?w=1200&h=1200&v=202407011736&qs=ignore','https://madeinbrazil.fbitsstatic.net/img/p/guitarra-strinberg-les-paul-lps230-bk-preto-130359/343429.jpg?w=1200&h=1200&v=202407011736&qs=ignore', 0 ,'Guitarra Strinberg Les Paul', 1.700)");
            migrationBuilder.Sql("INSERT INTO Instrumentos(CategoriaId,Resumo,ResumoDetalhada,EmEstoque,ImagemThumbnailUrl,ImagemUrl,Destaque,InstrumentoNome,Preco) VALUES(1,'Guitarra Tagima Jazz Master TW-60 - Metallic Deep Silver','A linha Woodstock Series é uma releitura de modelos clássicos de guitarra e baixo oferecidos pela Tagima. Projetadas no Brasil e fabricadas em fábricas pelo mundo todo, as Tagima Woodstock Series são a linha de entrada da Tagima que une o visual clássico de modelos marcados pela história.',1,'https://madeinbrazil.fbitsstatic.net/img/p/guitarra-tagima-jazz-master-tw-60-metallic-deep-silver-130354/343424.jpg?w=1200&h=1200&v=202406281800&qs=ignore','https://madeinbrazil.fbitsstatic.net/img/p/guitarra-tagima-jazz-master-tw-60-metallic-deep-silver-130354/343424.jpg?w=1200&h=1200&v=202406281800&qs=ignore',0,'Guitarra Tagima Jazz Master TW-60', 1.300)");
            migrationBuilder.Sql("INSERT INTO Instrumentos(CategoriaId,Resumo,ResumoDetalhada,EmEstoque,ImagemThumbnailUrl,ImagemUrl,Destaque,InstrumentoNome,Preco) VALUES(1,'Guitarra EVH Wolfgang Special - Satin Surf Green','A Wolfgang Special possui um corpo em basswood e um braço robusto de maple quartersawn reforçado com grafite parafusado. O braço é esculpido e arredondado de acordo com as especificações exigentes de Eddie Van Halen. Preparado para alto desempenho, riffs energéticos e solos presentes, sua escala em maple de raio composto de 12\"-16\" possui 22 trastes jumbo e marcações de pontos pretos. Além de ajustes de tensor no heel-mount.',1,'https://madeinbrazil.fbitsstatic.net/img/p/guitarra-evh-wolfgang-special-satin-surf-green-130347/343417.jpg?w=1200&h=1200&v=202406251659&qs=ignore','https://madeinbrazil.fbitsstatic.net/img/p/guitarra-evh-wolfgang-special-satin-surf-green-130347/343417.jpg?w=1200&h=1200&v=202406251659&qs=ignore',0,'Guitarra EVH Wolfgang Special ', 13.900)");
            migrationBuilder.Sql("INSERT INTO Instrumentos(CategoriaId,Resumo,ResumoDetalhada,EmEstoque,ImagemThumbnailUrl,ImagemUrl,Destaque,InstrumentoNome,Preco) VALUES(1,'Guitarra EVH Series Deluxe QM - Purple Daze','A 5150 Deluxe QM possui corpo em basswood no estilo Strato, modificado com um tampo em maple. O braço em maple quartersawn com reforço de grafite apresenta um shape confortável em \"C\", ajustes no tensor do heel-mount e headstock combinado de cor com decalque do logotipo EVH. Feito para uma tocabilidade suave e rápida, a escala composta de raio 12\"-16\" em ebony possui 22 trastes jumbo e marcações de ponto creme.',1,'https://madeinbrazil.fbitsstatic.net/img/p/guitarra-evh-series-deluxe-qm-purple-daze-130346/343416.jpg?w=1200&h=1200&v=202406251158&qs=ignore','https://madeinbrazil.fbitsstatic.net/img/p/guitarra-evh-series-deluxe-qm-purple-daze-130346/343416.jpg?w=1200&h=1200&v=202406251158&qs=ignore',1,'Guitarra EVH Series Deluxe QM', 13.900)");

            migrationBuilder.Sql("INSERT INTO Instrumentos(CategoriaId,Resumo,ResumoDetalhada,EmEstoque,ImagemThumbnailUrl,ImagemUrl,Destaque,InstrumentoNome,Preco) VALUES(2,'Contrabaixo Fender 4C Player Jazz Bass Canhoto - Polar White','Com seus captadores duplos single-coil e toque suave, o Player Jazz Bass canhoto é um instrumento inspirador com estilo clássico e elevado e timbre de baixo autêntico da Fender. É um som poderoso e estrondoso, forte e firme que combina com uma sensação de execução rápida e suave para uma dose de inspiração criativa. Pronto para ação no estúdio ou no palco, o Player Jazz Bass pode aguentar tudo o que você imaginar - e tudo o que você ainda não fez.',1, 'https://madeinbrazil.fbitsstatic.net/img/p/contrabaixo-fender-4c-player-jazz-bass-canhoto-polar-white-130213/343281.jpg?w=1200&h=1200&v=no-change&qs=ignore','https://madeinbrazil.fbitsstatic.net/img/p/contrabaixo-fender-4c-player-jazz-bass-canhoto-polar-white-130213/343281.jpg?w=1200&h=1200&v=no-change&qs=ignore', 0 ,'Contrabaixo Fender 4C ', 8.000)");
            migrationBuilder.Sql("INSERT INTO Instrumentos(CategoriaId,Resumo,ResumoDetalhada,EmEstoque,ImagemThumbnailUrl,ImagemUrl,Destaque,InstrumentoNome,Preco) VALUES(2,'Contrabaixo Fender Adam Clayton Jazz Bass - Sherwood Green Metallic','Contrabaixo Fender Adam Clayton Jazz Bass - Sherwood Green Metallic',1,'https://madeinbrazil.fbitsstatic.net/img/p/contrabaixo-fender-adam-clayton-jazz-bass-sherwood-green-metallic-130296/343365.jpg?w=1200&h=1200&v=no-change&qs=ignore','https://madeinbrazil.fbitsstatic.net/img/p/contrabaixo-fender-adam-clayton-jazz-bass-sherwood-green-metallic-130296/343365.jpg?w=1200&h=1200&v=no-change&qs=ignore',0,'Contrabaixo Fender Adam Clayton', 28.600)");
            migrationBuilder.Sql("INSERT INTO Instrumentos(CategoriaId,Resumo,ResumoDetalhada,EmEstoque,ImagemThumbnailUrl,ImagemUrl,Destaque,InstrumentoNome,Preco) VALUES(2,'Contrabaixo Infantil PHX Precision Junior IPB-MRD - Vermelho','Introduzindo o Precision Bass, um clássico atemporal para os amantes do som encorpado. Construído com um corpo de basswood e um braço de maple, este baixo oferece um equilíbrio perfeito entre peso e tom. Equipado com 1 captador Precision Bass, este instrumento proporciona graves potentes e definidos. Sua equalização simples, com 1 controle de volume e 1 de tone, permite ajustar o som de forma intuitiva. As tarraxas cromadas mantêm a afinação precisa, e o acabamento em verniz brilhante realça sua beleza clássica.',1,'https://madeinbrazil.fbitsstatic.net/img/p/contrabaixo-infantil-phx-precision-junior-ipb-mrd-vermelho-130290/343359.jpg?w=1200&h=1200&v=no-change&qs=ignore','https://madeinbrazil.fbitsstatic.net/img/p/contrabaixo-infantil-phx-precision-junior-ipb-mrd-vermelho-130290/343359.jpg?w=1200&h=1200&v=no-change&qs=ignore',0,'Contrabaixo Infantil PHX', 1.250)");
            migrationBuilder.Sql("INSERT INTO Instrumentos(CategoriaId,Resumo,ResumoDetalhada,EmEstoque,ImagemThumbnailUrl,ImagemUrl,Destaque,InstrumentoNome,Preco) VALUES(2,'Contrabaixo Fender 4C Player Precision Bass - Candy Apple Red','Não há nada mais clássico do que um baixo elétrico Fender, e o Player Precision Bass é o mais autêntico possível - o estilo Fender genuíno e o som estrondoso e sísmico que gerou milhares de imitações. Com sua sensação de toque suave e estilo pronto para os holofotes, este baixo estrondoso está pronto para entrar no estúdio ou rondar o palco e ajudar a mostrar ao mundo sua visão criativa.',1,'https://madeinbrazil.fbitsstatic.net/img/p/contrabaixo-fender-4c-player-precision-bass-candy-apple-red-130214/343282.jpg?w=1200&h=1200&v=no-change&qs=ignore','https://madeinbrazil.fbitsstatic.net/img/p/contrabaixo-fender-4c-player-precision-bass-candy-apple-red-130214/343282.jpg?w=1200&h=1200&v=no-change&qs=ignore',1,'Contrabaixo Fender 4C ', 7.800)");

            migrationBuilder.Sql("INSERT INTO Instrumentos(CategoriaId,Resumo,ResumoDetalhada,EmEstoque,ImagemThumbnailUrl,ImagemUrl,Destaque,InstrumentoNome,Preco) VALUES(3,'Teclado Casio Casiotone CT-S1000V','Um tipo de voz que canta com o toque de uma tecla. O CT-S1000V é um instrumento que redefine o conceito de teclado e como ele é tocado. Em sua essência, está a nova tecnologia Vocal Synthesis da Casio, que lhe permite ir além da apresentação convencional, abrindo novas possibilidades criativas e dando liberdade para expressão musical. Capture esse momento de inspiração em tempo real e aproveite uma experiência musical única.',1, 'https://madeinbrazil.fbitsstatic.net/img/p/teclado-casio-casiotone-ct-s1000v-com-61-teclas-sensitivas-129686/342753.jpg?w=1200&h=1200&v=no-change&qs=ignore','https://madeinbrazil.fbitsstatic.net/img/p/teclado-casio-casiotone-ct-s1000v-com-61-teclas-sensitivas-129686/342753.jpg?w=1200&h=1200&v=no-change&qs=ignore', 0 ,'Teclado Casio Casiotone CT-S1000V', 2.500)");
            migrationBuilder.Sql("INSERT INTO Instrumentos(CategoriaId,Resumo,ResumoDetalhada,EmEstoque,ImagemThumbnailUrl,ImagemUrl,Destaque,InstrumentoNome,Preco) VALUES(3,'Teclado Sintetizador Yamaha MODX8+ com 88 Teclas','MODX8+ - compacto e leve, o sintetizador MODX8+ 88 teclas com sons e dinâmica balanceada de Piano, instrumentos e sons de synth que os pianistas precisam para se destacar no palco, no estúdio ou durante transmissões ao vivo.',1,'https://madeinbrazil.fbitsstatic.net/img/p/teclado-sintetizador-yamaha-modx7-com-76-teclas-130018/343086.jpg?w=1200&h=1200&v=no-change&qs=ignore','https://madeinbrazil.fbitsstatic.net/img/p/teclado-sintetizador-yamaha-modx7-com-76-teclas-130018/343086.jpg?w=1200&h=1200&v=no-change&qs=ignore',0,'Teclado Sintetizador Yamaha MODX7+', 14.600)");
            migrationBuilder.Sql("INSERT INTO Instrumentos(CategoriaId,Resumo,ResumoDetalhada,EmEstoque,ImagemThumbnailUrl,ImagemUrl,Destaque,InstrumentoNome,Preco) VALUES(3,'Teclado Workstation Yamaha CK61 com 61 Teclas','O CK transforma qualquer lugar em um palco ou estúdio com controles intuitivos, alto-falantes discretos integrados e todos os sons que precisa para criar seu próprio som. O CK combina os sons do Stage Piano Yamaha CP com o Stage keyboard Yamaha YC focado em órgão e sintetizador para dar a você um banco sonoro totalmente novo. Você terá piano, pianos elétricos, cordas e metais, além de uma seção de órgão dedicada e sons de sintetizadores modernos. Efeitos especiais inclusos para deixá-los do seu jeito. Existe até uma entrada analógica para digital (A/D) para conectar um microfone ou outro instrumento, aplicar efeitos e gravar diretamente em seu laptop. Sem falar que o CK possui alto-falantes discretos integrados e possibilidade de usar pilhas, permitindo levar seu novo som a novos lugares.',1,'https://www.madeinbrazil.com.br/produto/teclado-workstation-yamaha-ck61-com-61-teclas-130332','https://www.madeinbrazil.com.br/produto/teclado-workstation-yamaha-ck61-com-61-teclas-130332',0,'Teclado Workstation Yamaha CK61', 8.950)");
            migrationBuilder.Sql("INSERT INTO Instrumentos(CategoriaId,Resumo,ResumoDetalhada,EmEstoque,ImagemThumbnailUrl,ImagemUrl,Destaque,InstrumentoNome,Preco) VALUES(3,'Teclado Arranjador Roland E-X20 A com 61 Teclas','Se você quer ser músico, tocar teclado é o jeito mais amplo de aprender tudo sobre música. Criado pela Roland - marca admirada por profissionais no mundo todo por sua história, qualidade e expressão - o E-X20A é o instrumento perfeito pra você começar sua vida na música. Os sons de piano de alta qualidade foram feitos pra ajudar no desenvolvimento musical, onde os timbres tradicionais são sempre exigidos. Além disso, este teclado também tem outras opções de sons internos, incluindo vários sons étnicos pra tocar ritmos regionais de qualquer lugar do mundo. Tocar sozinho no E-X20A é uma experiência única – com o arranjador embutido você toca com uma seção de acompanhamento completo, te preparando pra primeira experiência com banda ou orquestra.',1,'https://madeinbrazil.fbitsstatic.net/img/p/teclado-arranjador-roland-e-x20-a-com-61-teclas-127802/314287.jpg?w=1200&h=1200&v=no-change&qs=ignore','https://madeinbrazil.fbitsstatic.net/img/p/teclado-arranjador-roland-e-x20-a-com-61-teclas-127802/314287.jpg?w=1200&h=1200&v=no-change&qs=ignore',1,'Teclado Arranjador Roland E-X20 A', 1.600)");

        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("DELETE FROM Instrumentos");

        }
    }
}
